"""Action plan contract.

Structured plan generated by an agent to execute tools.
Immutable and JSON-serializable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Tuple


def _validate_text(value: str, field_name: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f'{field_name} must be a non-empty string')


def _validate_json_value(value: Any, field_name: str) -> None:
    if value is None:
        return
    if isinstance(value, (str, int, float, bool)):
        return
    if isinstance(value, list):
        for item in value:
            _validate_json_value(item, field_name)
        return
    if isinstance(value, dict):
        for key, item in value.items():
            if not isinstance(key, str):
                raise ValueError(f'{field_name} keys must be strings')
            _validate_json_value(item, field_name)
        return
    raise ValueError(f'{field_name} must be JSON-serializable')


@dataclass(frozen=True)
class ActionStep:
    """Single step in an action plan."""

    step_id: str
    tool: str
    description: str
    parameters: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        _validate_text(self.step_id, 'step_id')
        _validate_text(self.tool, 'tool')
        _validate_text(self.description, 'description')
        _validate_json_value(self.parameters, 'parameters')

    def to_dict(self) -> dict:
        return {
            'id': self.step_id,
            'tool': self.tool,
            'description': self.description,
            'parameters': self.parameters
        }


@dataclass(frozen=True)
class ActionPlan:
    """Immutable action plan that can be serialized to JSON."""

    ticket_id: int | None
    summary: str
    steps: Tuple[ActionStep, ...] = field(default_factory=tuple)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.ticket_id is not None and not isinstance(self.ticket_id, int):
            raise ValueError('ticket_id must be an integer when provided')
        _validate_text(self.summary, 'summary')

        steps = self.steps
        if isinstance(steps, list):
            steps = tuple(steps)
        elif not isinstance(steps, tuple):
            raise ValueError('steps must be a tuple or list of ActionStep')
        for step in steps:
            if not isinstance(step, ActionStep):
                raise ValueError('steps must contain ActionStep items')

        _validate_json_value(self.metadata, 'metadata')
        object.__setattr__(self, 'steps', steps)

    def to_dict(self) -> dict:
        return {
            'ticket_id': self.ticket_id,
            'summary': self.summary,
            'steps': [step.to_dict() for step in self.steps],
            'metadata': self.metadata
        }
